"""
..
    /------------------------------------------------------------------------------\
    |                 -- FACADE TECHNOLOGIES INC.  CONFIDENTIAL --                 |
    |------------------------------------------------------------------------------|
    |                                                                              |
    |    Copyright [2019] Facade Technologies Inc.                                 |
    |    All Rights Reserved.                                                      |
    |                                                                              |
    | NOTICE:  All information contained herein is, and remains the property of    |
    | Facade Technologies Inc. and its suppliers if any.  The intellectual and     |
    | and technical concepts contained herein are proprietary to Facade            |
    | Technologies Inc. and its suppliers and may be covered by U.S. and Foreign   |
    | Patents, patents in process, and are protected by trade secret or copyright  |
    | law.  Dissemination of this information or reproduction of this material is  |
    | strictly forbidden unless prior written permission is obtained from Facade   |
    | Technologies Inc.                                                            |
    |                                                                              |
    \------------------------------------------------------------------------------/

This module contains the code for the manage project dialog.
"""

from PySide2.QtWidgets import QDialog, QWidget, QAbstractButton
from PySide2.QtCore import Signal

from data.project import Project
# uses this autogenerated python file to create dialog structure.
from gui.ui.ui_manageprojectdialog import Ui_Dialog as Ui_ManageProjectDialog
import gui.facileview as fv

# TODO: get rid of this once Project backend gets switched to enums.
backends = ["WIN32", "UIA", "Other"]


class ManageProjectDialog(QDialog):
	"""
	This class is used to show settings for Facile and for the currently opened project, if available.
	"""

	projectUpdated = Signal()
	
	def __init__(self, project: Project, mainWindow: 'FacileView', parent: QWidget = None):
		"""
		Constructs a ManageProjectDialog object.
		
		:param parent: the widget to nest this dialog inside of. If None, this dialog will be a window.
		:type parent: PySide2.QtWidgets.QWidget
		"""
		
		super(ManageProjectDialog, self).__init__(parent)
		self.ui = Ui_ManageProjectDialog()
		self.ui.setupUi(self)
		self.setWindowTitle("Manage Project")

		self.mainWindow: fv.FacileView = mainWindow
		self._project = project

		self.initializeValues()
		self.connectSignals()

		self.ui.buttonBox.clicked.connect(lambda button: self.applySettings(button))

		if project:
			self.ui.project_tab.setEnabled(True)
			# self.ui.target_gui_model_tab.setEnabled(True)  # TODO: Enable these when model theming is functional
			# self.ui.api_model_tab.setEnabled(True)

			self.ui.locationEdit.setText(project.getProjectDir())
			self.ui.nameEdit.setText(project.getName())
			self.ui.descriptionEdit.setText(project.getDescription())
			self.ui.appEdit.setText(project.getExecutableFile())
			if project.getBackend() in backends:
				idx = backends.index(project.getBackend())
			else:
				idx = 2
			self.ui.backendEdit.setCurrentIndex(idx)
			if project.autoCloseAppOnExit:
				self.ui.closeAppConf.setChecked(project.autoCloseAppOnExit)

	def connectSignals(self):
		"""
		Connects any signals needed for proper behavior of the dialog
		"""
		# TODO: Enable color choosing for component graphics, where this will be needed. Not a priority at the moment.
		pass

	def initializeValues(self):
		"""
		Initializes all the user settings to be visible/selected
		"""
		self.ui.enableSBs.setChecked(self.mainWindow.scrollBarsEnabled())
		self.setInitTheme()
		self.setInitLayout()

	def setInitTheme(self):
		"""
		Sets the theme box to have the current theme
		"""
		self.ui.themeBox.setCurrentIndex(self.mainWindow.getTheme().value - 1)

	def setInitLayout(self):
		"""
		Sets the layout box to have the current layout
		"""
		self.ui.layoutBox.addItems(["Models Only", "Essentials", "Classic", "All"])
		self.ui.layoutBox.setCurrentIndex(self.mainWindow.getLayout().value - 1)

	def applySettings(self, button: QAbstractButton = None, bypass=False):
		"""
		If apply is pressed, apply the settings without closing the window
		"""

		if bypass or button.text() == 'Apply':
			if self._project:
				self._project.setBackend(self.ui.backendEdit.currentText())
				self._project.setName(self.ui.nameEdit.text())
				self._project.setProjectDir(self.ui.locationEdit.text())
				self._project.setDescription(self.ui.descriptionEdit.toPlainText())
				self._project.setExecutableFile(self.ui.appEdit.text())

				if self._project.acaWarningShown:
					if self.ui.closeAppConf.isChecked():
						self._project.autoCloseAppOnExit = True
					else:
						self._project.autoCloseAppOnExit = False

			self.mainWindow.setTheme(fv.FacileView.Theme(self.ui.themeBox.currentIndex() + 1))
			if self.ui.layoutBox.currentIndex() < 4:
				self.mainWindow.setLayout(fv.FacileView.Layout(self.ui.layoutBox.currentIndex() + 1))
			else:
				self.mainWindow.setLayout(fv.FacileView.Layout.CLASSIC)
			self.mainWindow.enableScrollBars(self.ui.enableSBs.isChecked())
			self.mainWindow.saveSettings()
	
	def accept(self) -> None:
		"""
		Called when the user clicks the "OK" button.
		
		:return: None
		:rtype: NoneType
		"""

		self.applySettings(bypass=True)

		QDialog.accept(self)
	
	def reject(self) -> None:
		"""
		Called when the user clicks the "close" button.

		:return: None
		:rtype: NoneType
		"""
		
		QDialog.reject(self)
