include "libs\\env.py"
include "tguiil\\matchoption.py"
include "tguiil\\tokens.py"
include "data\\entity.py"
include "data\\property.py"
include "data\\properties.py"
include "data\\tguim\\condition.py"
include "data\\tguim\\visibilitybehavior.py"
include "tguiil\\supertokens.py"
include "data\\tguim\\component.py"
include "data\\tguim\\targetguimodel.py"
include "tguiil\\application.py"
include "tguiil\\componentfinder.py"

include "baseapplication.py"
# ORDER IS IMPORTANT
