
name = "click"
description = "Left-click a component."
targets = {'Button', 'MenuItem', '_treeview_element', '_toolbar_element', '_listview_element'}
inputs = []
outputs = []
code = """
comp.set_focus()
comp.click()
"""