
name = "Click"
description = "Left-clicks component {id}."
targets = {'Button', '_treeview_element', '_toolbar_element', '_listview_element'}
inputs = []
outputs = []
code = """
comp.set_focus()
comp.click()
"""