name = "read"
description = "Read from a component."
targets = {'Edit', 'Static'}
inputs = []
outputs = [
	{
		"name": "value",
		"description": "Value obtained from reading component text.",
		"type": str,
	}
]
code = """
return comp.get_value()
"""