name = "Read_Text"
description = "Reads text from component {id}."
targets = {'Edit', 'Static'}
inputs = []
outputs = [
	{
		"name": "value",
		"description": "Value obtained from reading component text.",
		"type": str,
	}
]
code = """
return comp.get_value()
"""