name = "write"
description = "Write to a component, overwriting any existing text."
targets = ['Edit']
inputs = [
	{
		"name": "value",
		"type": str,
		"description": "Value to be written.",
		"optional": False
	}
]
outputs = []
code = """
comp.set_edit_text(value)
"""