name = "Set Text"
description = "Overwrites the contents of component {id} with contents of 'value'."
targets = ['Edit']
inputs = [
	{
		"name": "value",
		"data type": str,
		"description": "Text to be written.",
		"optional": False
	}
]
outputs = []
code = """
comp.set_edit_text(value)
"""