name = "Write"
description = "Write to a component. Will be added to any existing text."
targets = ['Edit']
inputs = [
	{
		"name": "value",
		"type": str,
		"description": "Value to be written.",
		"optional": False
	}
]
outputs = []
code = """
comp.type_keys(value, with_spaces=True)
"""