name = "Write"
description = "Writes the contents of 'value' to component {id}. Will be added to any existing text."
targets = ['Edit']
inputs = [
	{
		"name": "value",
		"data type": str,
		"description": "Text to be written.",
		"optional": False
	}
]
outputs = []
code = """
comp.type_keys(value, with_spaces=True)
"""