# This is a basic workflow to help you get started with Actions

name: Linter

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action for pylint
        uses: cclauss/GitHub-Action-for-pylint@0.7.0
